//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фасхиева_ПР6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.ClientPhoto = new HashSet<ClientPhoto>();
            this.SeasonTicket = new HashSet<SeasonTicket>();
        }
    
        public int idClient { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronimyc { get; set; }
        public string phone { get; set; }
        public System.DateTime birthday { get; set; }
        public int idGender { get; set; }
        public string login { get; set; }
        public int password { get; set; }
        public int idRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPhoto> ClientPhoto { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonTicket> SeasonTicket { get; set; }
    }
}
