//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фасхиева_ПР6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPhoto
    {
        public int idPhoto { get; set; }
        public int idClient { get; set; }
        public byte[] photoBinary { get; set; }
        public string photoPath { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
