//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фасхиева_ПР6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CentrEntities : DbContext
    {
        public CentrEntities()
            : base("name=CentrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Instructors> Instructors { get; set; }
        public virtual DbSet<PassportData> PassportData { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SeasonTicket> SeasonTicket { get; set; }
        public virtual DbSet<Training> Training { get; set; }
    }
}
