//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фасхиева_ПР6
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportData
    {
        public int idPassport { get; set; }
        public int seria { get; set; }
        public int nomer { get; set; }
        public string division_code { get; set; }
    
        public virtual Instructors Instructors { get; set; }
    }
}
