//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фасхиева_ПР6
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonTicket
    {
        public int idTicket { get; set; }
        public int count { get; set; }
        public int idGroup { get; set; }
        public int idClient { get; set; }
        public double cost { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Group Group { get; set; }
    }
}
