//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Фасхиева_ПР6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int idTraining { get; set; }
        public int idInstruct { get; set; }
        public int idGroup { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Instructors Instructors { get; set; }
    }
}
